name: Build and Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

env:
  XCODE_VERSION: '13.4.1'
  JAVA_VERSION: '11'
  JAVA_DISTRIBUTION: 'corretto'

jobs:
  macos:
    name: Build on macos
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: "gradle"

      - name: Ios build
        run: |
          ./gradlew :shared:iosX64Test --stacktrace

  linux:
    name: Build on linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: "gradle"

      - name: Android unit tests
        run: |
          ./gradlew :shared:testDebugUnitTest --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"
      - name: Build APK
        run: ./gradlew :androidApp:assembleDebug --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: androidApp/build/outputs/apk/debug/androidApp-debug.apk
