name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: 'main'

env:
  XCODE_VERSION: '13.4.1'
  JAVA_VERSION: '14'

jobs:
  build:
    name: Build & Test
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Shared
        id: gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :shared:check --warning-mode all